# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktoWin', '0002_auto_20161116_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.CharField(default='tag', max_length=16, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=16, unique=True, verbose_name='Тег'),
        ),
    ]
