# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktoWin', '0004_auto_20161116_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterField(
            model_name='comment',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='Колличество лайков'),
        ),
        migrations.AlterField(
            model_name='post',
            name='commemt_count',
            field=models.IntegerField(default=0, verbose_name='Колличество комментариев'),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='Колличество лайков'),
        ),
    ]
