# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ktoWin', '0005_auto_20161207_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ktoWin.Game', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='ktoWin.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(max_length=30, unique=True, verbose_name='Ник'),
        ),
    ]
